###############################################################################
# User's configuration file for the ESMValTool
###############################################################################
---
# Diagnostics create tables? [true]/false
write_table: true
# Diagnostics create plots? [true]/false
write_plots: true
# Diagnositcs write NetCDF files? [true]/false
write_netcdf: true
# Set the console log level debug, [info], warning, error
log_level: info
# verbosity is deprecated and will be removed in the future
# verbosity: 1
# Exit on warning? true/[false]
exit_on_warning: false
# Plot file format? [ps]/pdf/png/eps/epsi
output_file_type: png
# text output file type
table_output_file_type: tex
# Destination directory
output_dir: ./esmvaltool_output
# Use netCDF compression true/[false]
compress_netcdf: false
# Save intermediary cubes in the preprocessor true/[false]
save_intermediary_cubes: true
# Remove the preproc dir if all fine
remove_preproc_dir: false
# Run at most this many tasks in parallel null/[1]/2/3/4/..
# Set to null to use the number of available CPUs.
# Make sure your system has enough memory for the specified number of tasks.
max_parallel_tasks: 1
# Path to custom config-developer file, to customise project configurations.
# See config-developer.yml for an example. Set to None to use the default
config_developer_file: null
# Get profiling information for diagnostics
# Only available for Python diagnostics
profile_diagnostic: false

# Rootpaths to the data from different projects (lists are also possible)
rootpath:
  # Rootpath to CMIP5 data
  CMIP5: /home/inca1/rcheca/ESMValTool/esmvaltool_input
  # Rootpath to OBS data
  OBS: ~/esmvaltool_input
  # Default
  default: /home/inca1/rcheca/ESMValTool/esmvaltool_input
  CMIP6: /home/inca1/rcheca/ESMValTool/esmvaltool_input
  CRESCENDO: /home/inca1/rcheca/ESMValTool/esmvaltool_input


# Directory structure for input data: [default]/BADC/DKRZ/ETHZ/etc
# See config-developer.yml for definitions.
drs:
  CMIP5: default
  CMIP6: default
  CRESCENDO: default
  AEROCOM: default
